site_name: Hello Pinnacle Engineering

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder

nav:
  - Hello Docs: index.md
  - reference.md
